# Generated by Django 2.2.2 on 2019-06-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
