# Generated by Django 2.2.2 on 2019-06-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20190620_0415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='quizapp.Profile'),
        ),
    ]
