# Generated by Django 2.2.2 on 2019-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20190627_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ontra_contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
