# Generated by Django 2.2.2 on 2019-11-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_profile_sms_concent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ontra_contact_id',
        ),
    ]
